### ISSUE TITLE
Ammo not saving.

### ISSUE THREAD

**Issue by ProjectLibertyRP** [HumanTree92/esx_extraitems#14] opened 2020-06-03 03:53 UTC
Hi,

When I use my weapon clip / box for my weapon everything works perfectly and the bullets load into the weapon. When I visit the server again, the bullets I loaded into my weapon are gone and are not stored in the database.

I don't know if this is a bugg, otherwise this might be a suggestion. It's quite annoying when you re-enter the server and the bullets are gone.

Sincerely,
Symon

**Comment by HumanTree92** [comment] 2020-06-04 05:20
Pretty sure this has something to do with the save time of a player.

**Comment by Duqino** [comment] 2020-06-07 10:54
I got the same problem. I had this too with disc-ammo. Its not saving the ammo amount. 

(adding ammo too into the weapon. Leave the server and join the server)
Does this script needs x time to save it into the database? (or anywhere else)

**Comment by HumanTree92** [comment] 2020-06-08 04:24
Not too sure. I had seen someone mention this in es_extended but not sure where the comment was. But i will look more into this issue when i can.

**Comment by HonorAlterium** [comment] 2020-06-09 01:23
Same problem here! Im on esx 1.2.0

**Comment by HumanTree92** [comment] 2020-06-09 09:08
If someone can test this out for me try buying an ammo clip & then do /save and relog and see if it saves.

**Comment by Duqino** [comment] 2020-06-09 10:53
save is not a working command on my server. So ill wait 30 min so the server will do it by itself.

**Comment by Timmyopp** [comment] 2020-06-09 11:19
Which inventory/weapon shop are you all using?

**Comment by Duqino** [comment] 2020-06-09 11:36
esx_inventoryhud. And im not using esx_shops. esx_inventoryhud has its own shop.

**Comment by Timmyopp** [comment] 2020-06-09 11:38
Pretty sure I got a fix, will drop it when I get home.

**Comment by Timmyopp** [comment] 2020-06-09 12:14
Can you drop here your config file of inventoryhud?

**Comment by Duqino** [comment] 2020-06-09 12:54
https://pastebin.com/YD2f0Fpf

**Comment by HonorAlterium** [comment] 2020-06-09 13:07
No, dont work. if i type /saveall, save the db data but dont save the ammo in the db table users, column loadout "WEAPON_PISTOL":{"ammo":0}. My opinion, the problem is related to AddAmmoToPed(GetPlayerPed(-1), hash, ammo), it seems that the natively loaded bullets are not recorded on the db by esx

**Comment by Timmyopp** [comment] 2020-06-09 13:31
Check out the SQL file that comes along with the inventory and use the right item name for the ammo needed.

**Comment by HumanTree92** [comment] 2020-06-09 16:02
I found the problem last night. I will fix it soon. It b/c ESX Changed that way it gets ammo

**Comment by Duqino** [comment] 2020-06-09 19:55
Great too hear you found the problem.

**Comment by Duqino** [comment] 2020-06-15 16:31
Do you know when you have time too fix the bug?

**Comment by HumanTree92** [comment] 2020-06-15 19:39
I do not know when. I am a very busy person bc I have over 8 different servers to maintain and I am falling behind now bc I have a broken toe and my pain meds do not help me focus.

**Comment by Duqino** [comment] 2020-06-15 20:53
Dude 8 server..... Get a life! :D :P I hope too  see the bug fix soon. I cant find another script that does what this script does

**Comment by HumanTree92** [comment] 2020-06-15 21:10
I do have a life lol. I spend more time now planning for my wedding. And spending time with friends more then I work on my servers. I work on servers for a living. That's how I make most my money now a days. Kinda hard to go out and doing anything with all this Covid and BLM bs that's going on.

**Comment by Timmyopp** [comment] 2020-06-16 08:36
Duqino message me on discord Timmy#8488

**Comment by Duqino** [comment] 2020-06-23 17:47
@HumanTree92 Can you point us in the right direction so (maybe) we can fix this problem ourself?

**Comment by HumanTree92** [comment] 2020-06-23 17:58
Yeah sorry. If you fix it do a PR and i will accept it when i can. You can find more about it [here](https://github.com/dutchplayers/ESX-1.2-Inventory-HUD/issues/83)

**Comment by msmaiaa** [comment] 2020-07-01 09:54
Fixed this problem and pulled, im a web developer and this is my first time messing with lua and fivem stuff, sorry for the spaghetti code xD https://github.com/HumanTree92/esx_extraitems/pull/16

**Comment by msmaiaa** [comment] 2020-07-01 10:05
it doesnt work because you need to use the esx function in order to store it on the database, using the AddAmmoToPed function from fiveM its like spawning guns and cars with a menu, it wont save on the db and they will disappear when you disconnect

**Comment by HumanTree92** [comment] 2020-07-01 19:16
Should be fixed in https://github.com/HumanTree92/esx_extraitems/commit/bb967eba54a895913bbbc67f1ba65aef5213c519 thanks to https://github.com/msmaiaa in https://github.com/HumanTree92/esx_extraitems/pull/16

**Closed as completed by HumanTree92** 2020-07-01 19:16 UTC
Labels: Bug

**Comment by Duqino** [comment] 2020-07-02 18:41
I gues this fix is for the latest version for ESX. Because it doenst work for me.

SCRIPT ERROR: @es_extended/server/classes/player.lua:406: attempt to perform arithmetic on a nil value (field 'ammo')
> ref (@es_extended/server/classes/player.lua:406)
> handler (@esx_extraitems/server/main.lua:177)

**Comment by msmaiaa** [comment] 2020-07-02 21:35
@Duqino im using esx 1.2, what version are you using? Try a fresh install of esx extraitems

**Comment by Duqino** [comment] 2020-07-03 16:04
Im using 1.2 but not the lateste. I checked the player.lua and its different then im using. They removed essentialmode. So updating is kinda messed up.

**Comment by HumanTree92** [comment] 2020-07-04 01:26
@Duqino  Ain't no way your using 1.2 lol. As the error your having is https://github.com/esx-framework/es_extended/blob/1.2.0/server/classes/player.lua#L406 but esx_extraitems doesn't use that line

**Comment by Valkyrionas** [comment] 2020-10-16 19:23
Hey there, I got exactly the same Problem, I reworked my reply from yesterday, due to continously testing... I upgraded my old version of esx_extraitems to this, but it seems I need to adjust some code in es_extended due to how ammo is stored differently, it does work properly if u just have for example just 1 pistol, 1 mp, 1 rifle 1 marksmanship, but it does not work with as example 2 guns of the same weap-class (.50 pistol & pistol as example) with different magazine sizes. then it wont be stored from logoff to the next login. Im reading the code in esx_extended but Im not able to clearly code a workaround on getting esx_extraitems work on more than one weapon of the same class with different magazine sizes as mentioned above, can anyone help me or give me the input how I can adjust my es_extended (v1.2) to make this work properly ? would be very thankful.... or give me a hint on the codelines which I need to adjust to make it work synch as intended.
Im using the simple ammo with big and small boxes from esx_extraitems.

best regards!

**Comment by Valkyrionas** [comment] 2020-10-17 10:04
*update*
as I figured out now... the Ammo does store until Server-Restart. And it depends if u have "default" ammo from the weaponshop or PD (not from clips/boxes) still in your weapon-loadout, it seems that the ammo differs in code regarding from PD Armory/Weaponshop and from esx_extraitem via shop-items..

**Comment by HumanTree92** [comment] 2020-11-21 18:35
To lighten this issue what you could do is when a player uses a weapon clip then you could send a Server Event to save the player. Now as far as weapon ammo being shared between the same types of weapons that isn't any issue with my script or any script. Its an issue with GTA's logic.
